import type { Metadata } from 'next'
import { Montserrat, Poppins } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify desired weights
  variable: '--font-poppins'
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify desired weights
  variable: '--font-montserrat'
})

export const metadata: Metadata = {
  title: 'Tukerin Aja',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      url: '/favicon.svg'
    }
  ]
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
      >
        <NextTopLoader />
        {children}
      </body>
    </html>
  )
}
